name: Security Analysis

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 3 * * 1'

jobs:
  analyze:
    name: Run CodeQL & Dependabot check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4fca0d53a73580b2d64a5d8f48b3c8799e9e7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@e5d0fc5b8fb5b8f1e1c3c17a236e1d873582b1c1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@e5d0fc5b8fb5b8f1e1c3c17a236e1d873582b1c1

  dependabot:
    name: Dependabot vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@7fbebd80565aa3cfc66e53ec6c8cc99a98c6f6d3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}